### PR TITLE
Run CI for every PR

### PR DESCRIPTION
**Pull request by OskarStark**

### CODE REVIEW

**Review by alcaeus — APPROVED** [review]

**Comment by OskarStark** [comment]
I get the same error on my machine:
CleanShot 2023-12-01 at 10 22 25

**Review by GromNaN — APPROVED** [review]

**Comment by GromNaN** [comment]
Thank you @OskarStark

**Comment by OskarStark** [comment]
Any clue why the tests are failing ?

**Comment by OskarStark** [comment]
Symfony is facing the same issue:
CleanShot 2023-12-07 at 05 06 51@2x

**Pull request merged**
